version: '3.7'

networks:
  vsu-schedule-network:
    name: vsu-schedule-network
    driver: bridge


services:
  schedule-service:
    image: schedule-service:latest
    ports:
      - '9898:9898'
    networks:
      - vsu-schedule-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/schedule-db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./init-scripts-db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    networks:
      - vsu-schedule-network


  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0.0
    command: start-dev
    ports:
      - '8080:8080'
    networks:
      - vsu-schedule-network
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/keycloak-db
      - KC_DB_USERNAME=admin
      - KC_DB_PASSWORD=admin
      - KC_DB_SCHEMA=public
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
    depends_on:
      - db
